#!/bin/zsh
set -e

# don't reformat files which haven't been staged for commit
printf "Formatting with prettier...\n"
npm run lint-and-fix && npm run prettier-format

# don't add files which haven't already been staged for commit
# also (--diff-filter=d) don't try to add files which have been deleted
git add $(git diff --name-only --cached --diff-filter=d)
printf "\n"